apiVersion: v1
kind: ConfigMap
metadata:
  name: json-aggregator-config
data:
  json-aggregator.json: |-
    [
      {
          "namespace":"TestMinutesGrouped",
          "timeHorizons":["SECOND", "MINUTE", "MINUTES_GROUPED(5)", "HOUR"],
          "type":"SUM",
          "dataExtractor":"JSON",
          "labelItems":["metric_name", "uid"],
          "emitMetrics":"false",
          "summaryItems": ["max(metric_value)","min(metric_value)", "sum(metric_value)"],
          "dateItem": "timestamp"
      }
    ]
